export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const PAYMENT_ACTION = 'PAYMENT_ACTION';
export const BUY_WITHOUT_ACCOUNT_ACTION = 'BUY_WITHOUT_ACCOUNT_ACTION';
export const CLEAR_CART = 'CLEAR_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';